// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABKZT9_5-GxR8MxILYq5wcVzVnBxK-4yI',
    appId: '1:908287668476:web:b4105f562b32c8d4d42779',
    messagingSenderId: '908287668476',
    projectId: 'kendaraan-sehat',
    authDomain: 'kendaraan-sehat.firebaseapp.com',
    storageBucket: 'kendaraan-sehat.firebasestorage.app',
    measurementId: 'G-VR4FXNKB0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe2fXSM__McJf4lBooTnCQ6xi2l1Efs_U',
    appId: '1:908287668476:android:e77f816a655ca8bad42779',
    messagingSenderId: '908287668476',
    projectId: 'kendaraan-sehat',
    storageBucket: 'kendaraan-sehat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIstpFIi5H8rDMh-O1E0D6lxJccIGAaJw',
    appId: '1:908287668476:ios:12ecc7c3d9b423d4d42779',
    messagingSenderId: '908287668476',
    projectId: 'kendaraan-sehat',
    storageBucket: 'kendaraan-sehat.firebasestorage.app',
    iosClientId: '908287668476-8smaqa0pma3nj8e309sr0oqi7rh19kdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kendaraansehat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIstpFIi5H8rDMh-O1E0D6lxJccIGAaJw',
    appId: '1:908287668476:ios:12ecc7c3d9b423d4d42779',
    messagingSenderId: '908287668476',
    projectId: 'kendaraan-sehat',
    storageBucket: 'kendaraan-sehat.firebasestorage.app',
    iosClientId: '908287668476-8smaqa0pma3nj8e309sr0oqi7rh19kdd.apps.googleusercontent.com',
    iosBundleId: 'com.example.kendaraansehat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABKZT9_5-GxR8MxILYq5wcVzVnBxK-4yI',
    appId: '1:908287668476:web:42d8a64253ff12bfd42779',
    messagingSenderId: '908287668476',
    projectId: 'kendaraan-sehat',
    authDomain: 'kendaraan-sehat.firebaseapp.com',
    storageBucket: 'kendaraan-sehat.firebasestorage.app',
    measurementId: 'G-5N04LSN04B',
  );
}
